apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: file.csi.azure.com
    volumeHandle: <resource-group-name>#<storageAccountName>#<shareName>
    volumeAttributes:
      shareName: <shareName>
