apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketmq-pvc
  namespace: your-namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: rocketmq-pv   # force bind to our manual PV
  storageClassName: ""
